### ISSUE TITLE
Exception running Karma tests on Windows 10

### ISSUE THREAD

**Issue by mdurling** [aurelia/pal-browser#15]
**I'm submitting a bug report**

* **Library Version:**
aurelia-pal-browser@1.1.0

* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
Chrome 54.0.2840

* **Language:**
TypeScript 2.0.10

**Current behavior:**
aurelia-pal-browser exception when running karma on Windows 10. Do not get this exception on MacOS

**Expected/desired behavior:**
Karma tests should run without exception.

![image](https://cloud.githubusercontent.com/assets/3439869/20973292/1e972a06-bc66-11e6-96dc-0a2e0bd1189e.png)

**Comment by PWKad** [comment]
@mdurling Can you provide some repro steps?  Are you using the `skeleton-typescript-webpack` setup?  Trying to reproduce unsuccessfully so far.

**Comment by kuechlerm** [comment]
Get the same error. I repeat (google is not that good at reading texts from pngs... ):

```
Unhandled rejection TypeError: Cannot redefine property: title
    at Function.defineProperty (<anonymous>) [...]
```

Tracked it down to the call starting here: https://github.com/aurelia/pal-browser/blob/master/src/index.js#L53

But that is not the problem. I have a second project, where everything is fine with the same setup (aurelia-cli).

I deleted node_modules, did an `npm install`, `au build` then `au test` and now it works. Hooray, web development.

**Comment by mdurling** [comment]
@kuechlerm Glad to hear I am not alone! :-) Following your experience I did a `rmdir /S node_modules` and then `npm install` and the problem went away.

@PWKad Perhaps this will give you a hint at what was happening:

![image](https://cloud.githubusercontent.com/assets/3439869/21013040/8dd78c60-bd26-11e6-9123-174e23c6cb56.png)

The `initialize()` function was being called twice and `_aureliaPal.isInitialized` was `undefned` so the `Object.defineProperty` call throws an exception.

One thing I did notice was that before I deleted the `node_modules` folder, my npm packages looked like this:

```
+-- aurelia-bootstrapper-webpack@1.0.0
| `-- aurelia-pal@1.0.0
+-- aurelia-pal-browser@1.1.0
| `-- aurelia-pal@1.1.1
```

After I reinstalled the entire `node_modules` folder, my npm packages look like this:

```
+-- aurelia-bootstrapper-webpack@1.0.0
| `-- aurelia-pal@1.1.1
+-- aurelia-pal-browser@1.1.0
```

Maybe the issue has to do with `aurelia-bootstrapper-webpack` and `aurelia-pal-browser` using different versions of `aurelia-pal`

**Comment by PWKad** [comment]
@mdurling thanks for that going to check on it now!

**Comment by niieani** [comment]
@EisenbergEffect we could release one more `aurelia-bootstrapper-webpack` with a patch bump that updates the PAL dependency to fix this problem
