### ISSUE TITLE
replaceNode fails in IE11

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/pal-browser#16]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

* **Operating System:**
Windows 8.1

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **JSPM**
JSPM 0.16.29

* **Browser:**
IE 11

* **Language:**
TypeScript 2.0.3

**Current behavior:**
When loading a template with a `<slot>` tag, loading fails with this error:

```
Potentially unhandled rejection [7] TypeError: Unable to get property 'replaceChild' of undefined or null reference
   at replaceNode (eval code:3881:9)
   at makeShadowSlot (eval code:9008:5)
   at _compileElement (eval code:9213:11)
   at _compileNode (eval code:9069:11)
   at _compileNode (eval code:9090:13)
   at compile (eval code:9046:7)
   at Anonymous function (eval code:9589:11)
   at $ (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.24/system-polyfills.js:4:8727)
   at H (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.24/system-polyfills.js:4:8314)
   at R.prototype.when (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.24/system-polyfills.js:4:12046)
```

Some debugging reveals that for this error `replaceNode` is called with `<au-shadow-slot></au-shadow-slot>` for `newNode`, `<slot></slot>` for `node`, `null` for `node.parentNode` and `shadowPoly`, and `undefined` for `parentNode`.

**Expected/desired behavior:**
Template should load normally, as it does in all other major browsers.

**Comment by RomkeVdMeulen** [comment]
Correction: the presence of a `<slot>` tag in the template doesn't seem to be a factor. Debugging in IE11 isn't very straightforward and I'm having trouble pinning down the circumstances.

**Comment by RomkeVdMeulen** [comment]
At the moment our entire frontend is broken in IE so any advice would be greatly appreciated.

**Comment by RomkeVdMeulen** [comment]
Downgrading DI to 1.2.0 as suggested in aurelia/metadata#47 fixed this problem.

**Comment by altenstedt** [comment]
@RomkeVdMeulen Looks like this issue is getting resolved right now:

* https://github.com/aurelia/metadata/issues/47
* https://github.com/aurelia/templating-resources/issues/267
* https://github.com/aurelia/binding/issues/551

**Comment by RomkeVdMeulen** [comment]
And so it has.
