### ISSUE TITLE
`core-js` is missing as dependency

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/pal-browser#2]
When loading the `pal-browser` with `initialize` it uses `Object.assign` which isn't always defined.

**Comment by EisenbergEffect** [comment]
Fixed 08ab345af92d9ba8ddf2ba324a926e2e689c3adf

**Comment by stoffeastrom** [comment]
@EisenbergEffect I just tried it out and realised that there also needs to be a

```javascript
import 'core-js';
```
