### ISSUE TITLE
Error when calling Function.prototype.name in third party code

### ISSUE THREAD

**Issue by eberlitz** [aurelia/pal-browser#22]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.10.0

* **NPM Version:**
4.2.0

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.41

* **Browser:**
IE 11

* **Language:**
ESNext

**Current behavior:**
I'm using a third party library called Three.js and they use `Function.prototype.name` to check if a polyfill is required:

```js
if ( Function.prototype.name === undefined ) {
    // Missing in IE
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name
    Object.defineProperty( Function.prototype, 'name', {
        get: function () {
            return this.toString().match( /^\s*function\s*([^\(\s]*)/ )[ 1 ];
        }
    } );
}
```

The problem here is that just by calling `Function.prototype.name` we get an **Error: Cannot redefine non-configurable property 'name'** caused by the Aurelia pal-browser.

This error is throw in the redefinition of the name property in the code bellow:

https://github.com/aurelia/pal-browser/blob/1.2.1/dist/aurelia-pal-browser.js#L30

**Expected/desired behavior:**

* **What is the expected behavior?**

Not throw an error when calling `Function.prototype.name` in IE11. (I tested in the latest releases of Edge, Chrome and Firefox and they all work, IE11 is the problem here)

* **What is the motivation / use case for changing the behavior?**

Including third party libraries that can call `Function.prototype.name`.

**Comment by nenadvicentic** [comment]
Hi there,

Was there any outcome or is there workaround for this issue? Is not explicitly using `aurelia-pal-browser` sufficient?

**Comment by nenadvicentic** [comment]
OK, my problem was `object_hash` npm package. It is also mingling with `Function.prototype.name` property causing collision with Aurelia.

To fix this, in my case was enough to change:
`
const hash = hash(this.dto);
`

into:
`
const hash = hash(this.dto, { respectFunctionProperties: false, respectFunctionNames: false });
`

**Comment by eberlitz** [comment]
I need to use aurelia-pal-browser, my workaround for this was including my own polyfill before loading aurelia-pal-browser and three.js. So I ended up with 3 polyfills for the same thing (eww) but at least it works.

**Comment by EisenbergEffect** [comment]
Thanks for following up with the workaround all! Here's hoping for the day when we can drop most of these polyfills!
