### ISSUE TITLE
Move polyfills to another package

### ISSUE THREAD

**Issue by gheoan** [aurelia/pal-browser#23]
**I'm submitting a feature request**

* **Library Version:**
1.2.1

**Current behavior:**
`aurelia-pal-browser` contains polyfills that can't be removed.

**Expected/desired behavior:**

* **What is the expected behavior?**
`aurelia-pal-browser` depends on another package that contain the polyfills, similar to how `aurelia-polyfills` is handled.

* **What is the motivation / use case for changing the behavior?**
The use case is being able to remove or replace the polyfills.

**Comment by jods4** [comment]
Actually... you can't get rid of `aurelia-polyfills` that easily... it's the first thing imported by `aurelia-bootstrapper`.

If you use Webpack, you can remove all of them (aurelia-polyfills _and_ the ones in aurelia-pal) with option `features`:
https://github.com/aurelia/webpack-plugin/wiki/AureliaPlugin-options#features

**Comment by jods4** [comment]
To add an option for non-webpack users: what the plugin does is define some symbols that will trigger dead code removal by minifier.

For example if you use uglify to minify your code, you can remove the polyfills in `aurelia-pal` by using `--define FEATURE_NO_IE=true`. The list of symbols available is in the link above.

**Comment by EisenbergEffect** [comment]
@JeroenVinke Do we have a way via the Aurelia CLI to pass these symbols to UglifyJS for require and system-based builds?

**Comment by gheoan** [comment]
One method to get rid of `aurelia-polyfills` in the CLI is to include a file named `aurelia-polyfills` in the vendor bundle instead of the `aurelia-polyfills` package. I have tested this with the requirejs loader. I prefer this method because it requires only configuring the bundler and module loader, while the `FEATURE_NO_IE` requires additional build tools.

The polyfills from `pal-browser` could be moved to a new library on which `pal-brower` would depend, as long as that is not a breaking change, or to `aurelia-polyfills`, however I am not sure if that would interference with serverside rendering.

**Comment by EisenbergEffect** [comment]
Closing as it seems there's a solution and we've addressed this directly in vNext already.
