### ISSUE TITLE
TypeError: _aureliaPal.DOM.injectStyles is not a function

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/pal-browser#24]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.2

* **NPM Version:**
5.4.1

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
all

* **Language:**
TypeScript 2.5.2

**Current behavior:**
When the application starts I get the error on the subject, see [aurelia_error.zip](https://github.com/aurelia/pal-browser/files/1284270/aurelia_error.zip)

**Expected/desired behavior:**
The application is working properly using version 1.2.1

**Comment by JeroenVinke** [comment]
I just got this as well when I updated all Aurelia libraries in an app. I noticed that aurelia-pal-browser (in node_modules/aurelia-pal-browser) had a node_modules as well with just an aurelia-pal package in there. That aurelia-pal was 1.4.0 while the one in `node_modules/aurelia-pal` was 1.3.0 for some reason. Removing `node_modules` and running `npm install` again fixed the issue for me. I think this is an NPM issue

**Comment by enrico-padovani** [comment]
I always do `rimraf node_modules` :) I tried it again but I got the same error. Wierd

**Comment by bdefore** [comment]
I'm also encountering this issue, and I think @JeroenVinke is onto the cause: aurelia-pal-browser declares `^1.4.0` which gets with aurelia-pal of 1.4.0 while other dependencies seem to only get 1.3.0. here are my results of run `npm ls aurelia-pal` with both 1.2.1 and 1.3.0 of aurelia-pal-browser: https://gist.github.com/bdefore/563d5d998fa53c0e5fe807ac74ae870f

I'm running macOS 12, node v8.4.0, npm 5.3.0, and Webpack 3.8.1. Compiles fine, but I see the originally reported error as a runtime error immediately after aurelia-templating-resources report being configured.

Workaround for now is to pin to 1.2.1

**Comment by JeroenVinke** [comment]
If you have a yarn.lock or package-lock.json file in the project directory then be sure to remove it  before running npm install.

**Comment by bdefore** [comment]
@JeroenVinke thanks, removing package-lock.json fixed the issue for me and now all dependencies that were using 1.3.0 of aurelia-pal use 1.4.0 and everything runs fine. probably not related, but also updated to npm 5.5.1

**Comment by enrico-padovani** [comment]
The problem was definitely in package-lock.json, by removing it solved the problem. Thanks @JeroenVinke !

**Comment by JeroenVinke** [comment]
Thanks for the update

**Comment by Alexander-Taran** [comment]
for the ones who will end up here in the future

while upgrading some packages
got hit by this one as well but with yarn.lock
forcing the install  helped

Curious: depending only on au-bootstrapper produces chains of transit dependencies.
Might it be somehow related.
In a way that directly referenced dependencies do get bumped, but nested ones (logically) do not if they satisfy upper package.json
