### ISSUE TITLE
DOM !== PLATFORM.global.document

### ISSUE THREAD

**Issue by doktordirk** [aurelia/pal-browser#5]
i'd would have thought, they are the same. but it seems that when there is an unrecognized route, DOM.location is undefined whereas PLATFORM.global.document.location is that unrecognized location

**Comment by EisenbergEffect** [comment]
Interesting...

**Comment by doktordirk** [comment]
fyi: that's not happing with webpack for some reason

**Comment by rapitkan** [comment]
I'm facing this issue.

`aurelia-authentication.js:1387 Uncaught (in promise) TypeError: Cannot read property 'origin' of undefined
    at r.configure (http://localhost:9000/jspm_packages/npm/aurelia-authentication@3.0.0-rc4/aurelia-authentication.js:1387:39)
    at http://localhost:9000/jspm_packages/npm/aurelia-framework@1.0.0-beta.1.2.2/aurelia-framework.js:276:36`

Any ideas how to fix this?

**Comment by rapitkan** [comment]
I updated to 1.0.0-beta.3.0.0 and the problem disappeared.

**Comment by doktordirk** [comment]
note: yeah right:  as described in the docs, DOM never was supposed to be PLATFORM.global.document in the first place anyways
