### ISSUE TITLE
Unable to get property 'querySelectorAll' of undefined or null reference

### ISSUE THREAD

**Issue by ariovistus** [aurelia/pal-browser#9]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
4.1.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.42

* **Browser:**
IE 11, document mode Edge

* **Language:**
TypeScript 1.8

**Current behavior:**
in IE11, my app throws "Unable to get property 'querySelectorAll' of undefined or null reference" at line 73 of aurelia-loader:
```
requires = value.content.querySelectorAll('require');
```
content is undefined. 

**Expected/desired behavior:**

It seems the htmlTemplateElement test is not adequate for what createTemplateFromMarkup is doing, ie
```
'content' in document.createElement("template")
```
returns true, but 
```
var d = document.createElement("div");
d.innerHTML = "<template></template>";
'content' in d.children[0]
```
returns false.

* **What is the motivation / use case for changing the behavior?**
make my app not die in ie11

**Comment by EisenbergEffect** [comment]
It's virtually impossible to create a generic, fully functioning html template polyfill for browsers that don't support it (IE). So, we can't really make this work without over-writing the dom itself, which would be devastating for performance. I would recommend that you look into abstracting it yourself or using our PAL to create templates.

**Comment by ariovistus** [comment]
Wat? All the requisite manipulation of the dom is already there. It's just the test that guards it is not letting it get run when it looks like it should. It's a two line fix.
